// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addresses.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const clearDefaultAddress = `-- name: ClearDefaultAddress :exec
UPDATE addresses SET is_default = FALSE, updated_at = now()
WHERE user_id = $1 AND is_default = TRUE
`

func (q *Queries) ClearDefaultAddress(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultAddress, userID)
	return err
}

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (
    id, user_id, recipient_name, postal_code, street, number,
    complement, neighborhood, city, state, is_default
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, recipient_name, postal_code, street, number, complement, neighborhood, city, state, is_default, created_at, updated_at
`

type CreateAddressParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	RecipientName string
	PostalCode    string
	Street        string
	Number        string
	Complement    *string
	Neighborhood  string
	City          string
	State         string
	IsDefault     bool
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.ID,
		arg.UserID,
		arg.RecipientName,
		arg.PostalCode,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.Neighborhood,
		arg.City,
		arg.State,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipientName,
		&i.PostalCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :execrows
DELETE FROM addresses WHERE id = $1 AND user_id = $2
`

type DeleteAddressParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAddress, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, user_id, recipient_name, postal_code, street, number, complement, neighborhood, city, state, is_default, created_at, updated_at FROM addresses WHERE id = $1 AND user_id = $2
`

type GetAddressByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAddressByID(ctx context.Context, arg GetAddressByIDParams) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByID, arg.ID, arg.UserID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipientName,
		&i.PostalCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddressesByUser = `-- name: ListAddressesByUser :many
SELECT id, user_id, recipient_name, postal_code, street, number, complement, neighborhood, city, state, is_default, created_at, updated_at FROM addresses WHERE user_id = $1 ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListAddressesByUser(ctx context.Context, userID uuid.UUID) ([]Address, error) {
	rows, err := q.db.Query(ctx, listAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecipientName,
			&i.PostalCode,
			&i.Street,
			&i.Number,
			&i.Complement,
			&i.Neighborhood,
			&i.City,
			&i.State,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultAddress = `-- name: SetDefaultAddress :one
UPDATE addresses SET is_default = TRUE, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, recipient_name, postal_code, street, number, complement, neighborhood, city, state, is_default, created_at, updated_at
`

type SetDefaultAddressParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, setDefaultAddress, arg.ID, arg.UserID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipientName,
		&i.PostalCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses
SET recipient_name = $3, postal_code = $4, street = $5, number = $6,
    complement = $7, neighborhood = $8, city = $9, state = $10, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, recipient_name, postal_code, street, number, complement, neighborhood, city, state, is_default, created_at, updated_at
`

type UpdateAddressParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	RecipientName string
	PostalCode    string
	Street        string
	Number        string
	Complement    *string
	Neighborhood  string
	City          string
	State         string
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.UserID,
		arg.RecipientName,
		arg.PostalCode,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.Neighborhood,
		arg.City,
		arg.State,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipientName,
		&i.PostalCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
