// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_methods.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const findAuthMethodByUserAndProvider = `-- name: FindAuthMethodByUserAndProvider :one
SELECT id, user_id, provider, password_hash, provider_subject, created_at, last_used_at
FROM auth_methods
WHERE user_id = $1 AND provider = $2
`

type FindAuthMethodByUserAndProviderParams struct {
	UserID   uuid.UUID
	Provider string
}

func (q *Queries) FindAuthMethodByUserAndProvider(ctx context.Context, arg FindAuthMethodByUserAndProviderParams) (AuthMethod, error) {
	row := q.db.QueryRow(ctx, findAuthMethodByUserAndProvider, arg.UserID, arg.Provider)
	var i AuthMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.PasswordHash,
		&i.ProviderSubject,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertAuthMethodPassword = `-- name: InsertAuthMethodPassword :one
INSERT INTO auth_methods (id, user_id, provider, password_hash, created_at)
VALUES (gen_random_uuid(), $1, 'password', $2, now())
RETURNING id, user_id, provider, password_hash, provider_subject, created_at, last_used_at
`

type InsertAuthMethodPasswordParams struct {
	UserID       uuid.UUID
	PasswordHash *string
}

func (q *Queries) InsertAuthMethodPassword(ctx context.Context, arg InsertAuthMethodPasswordParams) (AuthMethod, error) {
	row := q.db.QueryRow(ctx, insertAuthMethodPassword, arg.UserID, arg.PasswordHash)
	var i AuthMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.PasswordHash,
		&i.ProviderSubject,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const touchAuthMethodLastUsed = `-- name: TouchAuthMethodLastUsed :exec
UPDATE auth_methods
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchAuthMethodLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAuthMethodLastUsed, id)
	return err
}

const updateAuthMethodPassword = `-- name: UpdateAuthMethodPassword :exec
UPDATE auth_methods
SET password_hash = $2,
    last_used_at = now()
WHERE user_id = $1 AND provider = 'password'
`

type UpdateAuthMethodPasswordParams struct {
	UserID       uuid.UUID
	PasswordHash *string
}

func (q *Queries) UpdateAuthMethodPassword(ctx context.Context, arg UpdateAuthMethodPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAuthMethodPassword, arg.UserID, arg.PasswordHash)
	return err
}
