// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart_items.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const countCartItems = `-- name: CountCartItems :one
SELECT COUNT(*) FROM cart_items WHERE cart_id = $1
`

func (q *Queries) CountCartItems(ctx context.Context, cartID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCartItems, cartID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCartItem = `-- name: DeleteCartItem :execrows
DELETE FROM cart_items WHERE id = $1 AND cart_id = $2
`

type DeleteCartItemParams struct {
	ID     uuid.UUID
	CartID uuid.UUID
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCartItem, arg.ID, arg.CartID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCartItemsByCart = `-- name: DeleteCartItemsByCart :exec
DELETE FROM cart_items WHERE cart_id = $1
`

func (q *Queries) DeleteCartItemsByCart(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCartItemsByCart, cartID)
	return err
}

const getCartItemByID = `-- name: GetCartItemByID :one
SELECT id, cart_id, variant_id, quantity, unit_price_cents, added_at, updated_at FROM cart_items WHERE id = $1 AND cart_id = $2
`

type GetCartItemByIDParams struct {
	ID     uuid.UUID
	CartID uuid.UUID
}

func (q *Queries) GetCartItemByID(ctx context.Context, arg GetCartItemByIDParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItemByID, arg.ID, arg.CartID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantUnitPrice = `-- name: GetVariantUnitPrice :one
SELECT COALESCE(cv.price_cents, cp.base_price_cents)::bigint AS unit_price_cents
FROM catalog_variants cv
JOIN catalog_products cp ON cp.id = cv.product_id
WHERE cv.id = $1
`

func (q *Queries) GetVariantUnitPrice(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getVariantUnitPrice, id)
	var unit_price_cents int64
	err := row.Scan(&unit_price_cents)
	return unit_price_cents, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT id, cart_id, variant_id, quantity, unit_price_cents, added_at, updated_at FROM cart_items WHERE cart_id = $1 ORDER BY added_at
`

func (q *Queries) ListCartItems(ctx context.Context, cartID uuid.UUID) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.VariantID,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items SET quantity = $3, updated_at = now()
WHERE id = $1 AND cart_id = $2
RETURNING id, cart_id, variant_id, quantity, unit_price_cents, added_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	ID       uuid.UUID
	CartID   uuid.UUID
	Quantity int32
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ID, arg.CartID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (id, cart_id, variant_id, quantity, unit_price_cents)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
ON CONFLICT (cart_id, variant_id) DO UPDATE
SET quantity = LEAST(cart_items.quantity + EXCLUDED.quantity, 99),
    unit_price_cents = EXCLUDED.unit_price_cents,
    updated_at = now()
RETURNING id, cart_id, variant_id, quantity, unit_price_cents, added_at, updated_at
`

type UpsertCartItemParams struct {
	CartID         uuid.UUID
	VariantID      uuid.UUID
	Quantity       int32
	UnitPriceCents int64
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem,
		arg.CartID,
		arg.VariantID,
		arg.Quantity,
		arg.UnitPriceCents,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}
