// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carts.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAnonCart = `-- name: CreateAnonCart :one
INSERT INTO carts (id, anon_session_id, status)
VALUES (gen_random_uuid(), $1, 'active')
RETURNING id, user_id, anon_session_id, status, created_at, updated_at
`

func (q *Queries) CreateAnonCart(ctx context.Context, anonSessionID *string) (Cart, error) {
	row := q.db.QueryRow(ctx, createAnonCart, anonSessionID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonSessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserCart = `-- name: CreateUserCart :one
INSERT INTO carts (id, user_id, status)
VALUES (gen_random_uuid(), $1, 'active')
RETURNING id, user_id, anon_session_id, status, created_at, updated_at
`

func (q *Queries) CreateUserCart(ctx context.Context, userID *uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, createUserCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonSessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAbandonedCarts = `-- name: DeleteAbandonedCarts :execrows
UPDATE carts SET status = 'abandoned', updated_at = now()
WHERE status = 'active' AND updated_at < $1 AND user_id IS NULL
`

func (q *Queries) DeleteAbandonedCarts(ctx context.Context, updatedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAbandonedCarts, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveCartByAnon = `-- name: GetActiveCartByAnon :one
SELECT id, user_id, anon_session_id, status, created_at, updated_at FROM carts WHERE anon_session_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveCartByAnon(ctx context.Context, anonSessionID *string) (Cart, error) {
	row := q.db.QueryRow(ctx, getActiveCartByAnon, anonSessionID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonSessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCartByUser = `-- name: GetActiveCartByUser :one
SELECT id, user_id, anon_session_id, status, created_at, updated_at FROM carts WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveCartByUser(ctx context.Context, userID *uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getActiveCartByUser, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnonSessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCartStatus = `-- name: SetCartStatus :exec
UPDATE carts SET status = $2, updated_at = now() WHERE id = $1
`

type SetCartStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetCartStatus(ctx context.Context, arg SetCartStatusParams) error {
	_, err := q.db.Exec(ctx, setCartStatus, arg.ID, arg.Status)
	return err
}
