// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO catalog_categories (id, slug, name, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, parent_id, created_at, updated_at
`

type CreateCategoryParams struct {
	ID       uuid.UUID
	Slug     string
	Name     string
	ParentID *uuid.UUID
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.ParentID,
	)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM catalog_categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, slug, name, parent_id, created_at, updated_at FROM catalog_categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, slug, name, parent_id, created_at, updated_at FROM catalog_categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, slug, name, parent_id, created_at, updated_at FROM catalog_categories ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]CatalogCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogCategory
	for rows.Next() {
		var i CatalogCategory
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE catalog_categories
SET name = $2, parent_id = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, name, parent_id, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID       uuid.UUID
	Name     string
	ParentID *uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.ParentID)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
