// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: charges.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createCharge = `-- name: CreateCharge :one
INSERT INTO charges (order_id, provider, provider_charge_id, method, status, amount_cents, raw_payload)
VALUES ($1, $2, $3, $4, 'pending', $5, $6)
RETURNING id, order_id, provider, provider_charge_id, method, status, amount_cents, raw_payload, created_at, updated_at
`

type CreateChargeParams struct {
	OrderID          uuid.UUID
	Provider         string
	ProviderChargeID string
	Method           string
	AmountCents      int64
	RawPayload       []byte
}

func (q *Queries) CreateCharge(ctx context.Context, arg CreateChargeParams) (Charge, error) {
	row := q.db.QueryRow(ctx, createCharge,
		arg.OrderID,
		arg.Provider,
		arg.ProviderChargeID,
		arg.Method,
		arg.AmountCents,
		arg.RawPayload,
	)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.Method,
		&i.Status,
		&i.AmountCents,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChargeByOrder = `-- name: GetChargeByOrder :one
SELECT id, order_id, provider, provider_charge_id, method, status, amount_cents, raw_payload, created_at, updated_at FROM charges WHERE order_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetChargeByOrder(ctx context.Context, orderID uuid.UUID) (Charge, error) {
	row := q.db.QueryRow(ctx, getChargeByOrder, orderID)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.Method,
		&i.Status,
		&i.AmountCents,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChargeByProviderID = `-- name: GetChargeByProviderID :one
SELECT id, order_id, provider, provider_charge_id, method, status, amount_cents, raw_payload, created_at, updated_at FROM charges WHERE provider = $1 AND provider_charge_id = $2
`

type GetChargeByProviderIDParams struct {
	Provider         string
	ProviderChargeID string
}

func (q *Queries) GetChargeByProviderID(ctx context.Context, arg GetChargeByProviderIDParams) (Charge, error) {
	row := q.db.QueryRow(ctx, getChargeByProviderID, arg.Provider, arg.ProviderChargeID)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.Method,
		&i.Status,
		&i.AmountCents,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasPaidCharge = `-- name: HasPaidCharge :one
SELECT EXISTS (SELECT 1 FROM charges WHERE order_id = $1 AND status = 'paid')
`

func (q *Queries) HasPaidCharge(ctx context.Context, orderID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPaidCharge, orderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :execrows
INSERT INTO payment_webhook_events (event_id, provider, charge_id)
VALUES ($1, $2, $3) ON CONFLICT (event_id) DO NOTHING
`

type InsertWebhookEventParams struct {
	EventID  string
	Provider string
	ChargeID *uuid.UUID
}

func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookEvent, arg.EventID, arg.Provider, arg.ChargeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setChargeStatus = `-- name: SetChargeStatus :exec
UPDATE charges SET status = $1, updated_at = now() WHERE id = $2
`

type SetChargeStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetChargeStatus(ctx context.Context, arg SetChargeStatusParams) error {
	_, err := q.db.Exec(ctx, setChargeStatus, arg.Status, arg.ID)
	return err
}
