// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkout_quotes.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createQuote = `-- name: CreateQuote :one
INSERT INTO checkout_quotes (user_id, cart_fingerprint, lines_snapshot, shipping_snapshot,
                             coupon_code, subtotal_cents, shipping_cents, discount_cents,
                             total_cents, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, cart_fingerprint, lines_snapshot, shipping_snapshot, coupon_code, subtotal_cents, shipping_cents, discount_cents, total_cents, expires_at, created_at
`

type CreateQuoteParams struct {
	UserID           uuid.UUID
	CartFingerprint  string
	LinesSnapshot    []byte
	ShippingSnapshot []byte
	CouponCode       *string
	SubtotalCents    int64
	ShippingCents    int64
	DiscountCents    int64
	TotalCents       int64
	ExpiresAt        time.Time
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (CheckoutQuote, error) {
	row := q.db.QueryRow(ctx, createQuote,
		arg.UserID,
		arg.CartFingerprint,
		arg.LinesSnapshot,
		arg.ShippingSnapshot,
		arg.CouponCode,
		arg.SubtotalCents,
		arg.ShippingCents,
		arg.DiscountCents,
		arg.TotalCents,
		arg.ExpiresAt,
	)
	var i CheckoutQuote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartFingerprint,
		&i.LinesSnapshot,
		&i.ShippingSnapshot,
		&i.CouponCode,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, user_id, request_hash, order_id, response, created_at FROM idempotency_keys WHERE user_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	UserID uuid.UUID
	Key    string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.RequestHash,
		&i.OrderID,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const getUserQuote = `-- name: GetUserQuote :one
SELECT id, user_id, cart_fingerprint, lines_snapshot, shipping_snapshot, coupon_code, subtotal_cents, shipping_cents, discount_cents, total_cents, expires_at, created_at FROM checkout_quotes WHERE id = $1 AND user_id = $2
`

type GetUserQuoteParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetUserQuote(ctx context.Context, arg GetUserQuoteParams) (CheckoutQuote, error) {
	row := q.db.QueryRow(ctx, getUserQuote, arg.ID, arg.UserID)
	var i CheckoutQuote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CartFingerprint,
		&i.LinesSnapshot,
		&i.ShippingSnapshot,
		&i.CouponCode,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const putIdempotencyKey = `-- name: PutIdempotencyKey :exec
INSERT INTO idempotency_keys (user_id, key, request_hash, order_id, response)
VALUES ($1, $2, $3, $4, $5)
`

type PutIdempotencyKeyParams struct {
	UserID      uuid.UUID
	Key         string
	RequestHash string
	OrderID     *uuid.UUID
	Response    []byte
}

func (q *Queries) PutIdempotencyKey(ctx context.Context, arg PutIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, putIdempotencyKey,
		arg.UserID,
		arg.Key,
		arg.RequestHash,
		arg.OrderID,
		arg.Response,
	)
	return err
}
