// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coupons.sql

package queries

import (
	"context"
	"time"
)

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (code, type, value, expires_at, usage_limit, min_order_cents)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, type, value, expires_at, usage_limit, used_count, min_order_cents, active, created_at
`

type CreateCouponParams struct {
	Code          string
	Type          string
	Value         int64
	ExpiresAt     *time.Time
	UsageLimit    *int32
	MinOrderCents *int64
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.Code,
		arg.Type,
		arg.Value,
		arg.ExpiresAt,
		arg.UsageLimit,
		arg.MinOrderCents,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.ExpiresAt,
		&i.UsageLimit,
		&i.UsedCount,
		&i.MinOrderCents,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, code, type, value, expires_at, usage_limit, used_count, min_order_cents, active, created_at FROM coupons WHERE code = $1
`

func (q *Queries) GetCouponByCode(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.ExpiresAt,
		&i.UsageLimit,
		&i.UsedCount,
		&i.MinOrderCents,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const redeemCoupon = `-- name: RedeemCoupon :one
UPDATE coupons SET used_count = used_count + 1
WHERE code = $1 AND active
  AND (usage_limit IS NULL OR used_count < usage_limit)
  AND (expires_at IS NULL OR expires_at > now())
RETURNING id, code, type, value, expires_at, usage_limit, used_count, min_order_cents, active, created_at
`

func (q *Queries) RedeemCoupon(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, redeemCoupon, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.ExpiresAt,
		&i.UsageLimit,
		&i.UsedCount,
		&i.MinOrderCents,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const releaseCoupon = `-- name: ReleaseCoupon :exec
UPDATE coupons SET used_count = used_count - 1
WHERE code = $1 AND used_count > 0
`

func (q *Queries) ReleaseCoupon(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, releaseCoupon, code)
	return err
}
