// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verify_tokens.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeEmailVerifyToken = `-- name: ConsumeEmailVerifyToken :exec
UPDATE email_verify_tokens
SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeEmailVerifyToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, consumeEmailVerifyToken, tokenHash)
	return err
}

const deleteExpiredEmailVerifyTokens = `-- name: DeleteExpiredEmailVerifyTokens :execrows
DELETE FROM email_verify_tokens
WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredEmailVerifyTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEmailVerifyTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findEmailVerifyToken = `-- name: FindEmailVerifyToken :one
SELECT token_hash, user_id, email, expires_at, consumed_at, created_at
FROM email_verify_tokens
WHERE token_hash = $1
`

func (q *Queries) FindEmailVerifyToken(ctx context.Context, tokenHash []byte) (EmailVerifyToken, error) {
	row := q.db.QueryRow(ctx, findEmailVerifyToken, tokenHash)
	var i EmailVerifyToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertEmailVerifyToken = `-- name: InsertEmailVerifyToken :exec
INSERT INTO email_verify_tokens (token_hash, user_id, email, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertEmailVerifyTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	Email     string
	ExpiresAt time.Time
}

func (q *Queries) InsertEmailVerifyToken(ctx context.Context, arg InsertEmailVerifyTokenParams) error {
	_, err := q.db.Exec(ctx, insertEmailVerifyToken,
		arg.TokenHash,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
	)
	return err
}
