// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const commitReservedStock = `-- name: CommitReservedStock :exec
UPDATE inventory_stock
SET reserved = reserved - $1, version = version + 1, updated_at = now()
WHERE variant_id = $2 AND reserved >= $1
`

type CommitReservedStockParams struct {
	Qty       int32
	VariantID uuid.UUID
}

func (q *Queries) CommitReservedStock(ctx context.Context, arg CommitReservedStockParams) error {
	_, err := q.db.Exec(ctx, commitReservedStock, arg.Qty, arg.VariantID)
	return err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO stock_reservations (order_id, variant_id, quantity, status, expires_at)
VALUES ($1, $2, $3, 'held', $4)
RETURNING id, order_id, variant_id, quantity, status, expires_at, created_at
`

type CreateReservationParams struct {
	OrderID   uuid.UUID
	VariantID uuid.UUID
	Quantity  int32
	ExpiresAt time.Time
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (StockReservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.OrderID,
		arg.VariantID,
		arg.Quantity,
		arg.ExpiresAt,
	)
	var i StockReservation
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VariantID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStock = `-- name: GetStock :one
SELECT variant_id, available, reserved, version, updated_at FROM inventory_stock WHERE variant_id = $1
`

func (q *Queries) GetStock(ctx context.Context, variantID uuid.UUID) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, getStock, variantID)
	var i InventoryStock
	err := row.Scan(
		&i.VariantID,
		&i.Available,
		&i.Reserved,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredHeldOrderIDs = `-- name: ListExpiredHeldOrderIDs :many
SELECT DISTINCT order_id FROM stock_reservations
WHERE status = 'held' AND expires_at < $1
`

func (q *Queries) ListExpiredHeldOrderIDs(ctx context.Context, expiresAt time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredHeldOrderIDs, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var order_id uuid.UUID
		if err := rows.Scan(&order_id); err != nil {
			return nil, err
		}
		items = append(items, order_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByOrder = `-- name: ListReservationsByOrder :many
SELECT id, order_id, variant_id, quantity, status, expires_at, created_at FROM stock_reservations WHERE order_id = $1
`

func (q *Queries) ListReservationsByOrder(ctx context.Context, orderID uuid.UUID) ([]StockReservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockReservation
	for rows.Next() {
		var i StockReservation
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VariantID,
			&i.Quantity,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseReservedStock = `-- name: ReleaseReservedStock :exec
UPDATE inventory_stock
SET available = available + $1, reserved = reserved - $1,
    version = version + 1, updated_at = now()
WHERE variant_id = $2 AND reserved >= $1
`

type ReleaseReservedStockParams struct {
	Qty       int32
	VariantID uuid.UUID
}

func (q *Queries) ReleaseReservedStock(ctx context.Context, arg ReleaseReservedStockParams) error {
	_, err := q.db.Exec(ctx, releaseReservedStock, arg.Qty, arg.VariantID)
	return err
}

const reserveStock = `-- name: ReserveStock :one
UPDATE inventory_stock
SET available = available - $1, reserved = reserved + $1,
    version = version + 1, updated_at = now()
WHERE variant_id = $2 AND available >= $1
RETURNING variant_id, available, reserved, version, updated_at
`

type ReserveStockParams struct {
	Qty       int32
	VariantID uuid.UUID
}

func (q *Queries) ReserveStock(ctx context.Context, arg ReserveStockParams) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, reserveStock, arg.Qty, arg.VariantID)
	var i InventoryStock
	err := row.Scan(
		&i.VariantID,
		&i.Available,
		&i.Reserved,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const setReservationStatus = `-- name: SetReservationStatus :execrows
UPDATE stock_reservations SET status = $1
WHERE order_id = $2 AND status = 'held'
`

type SetReservationStatusParams struct {
	NewStatus string
	OrderID   uuid.UUID
}

func (q *Queries) SetReservationStatus(ctx context.Context, arg SetReservationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setReservationStatus, arg.NewStatus, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertStock = `-- name: UpsertStock :one
INSERT INTO inventory_stock (variant_id, available, reserved, version)
VALUES ($1, $2, 0, 0)
ON CONFLICT (variant_id) DO UPDATE
SET available = EXCLUDED.available, version = inventory_stock.version + 1, updated_at = now()
WHERE inventory_stock.version = $3
RETURNING variant_id, available, reserved, version, updated_at
`

type UpsertStockParams struct {
	VariantID       uuid.UUID
	Available       int32
	ExpectedVersion int32
}

func (q *Queries) UpsertStock(ctx context.Context, arg UpsertStockParams) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, upsertStock, arg.VariantID, arg.Available, arg.ExpectedVersion)
	var i InventoryStock
	err := row.Scan(
		&i.VariantID,
		&i.Available,
		&i.Reserved,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
