// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Address struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	RecipientName string
	PostalCode    string
	Street        string
	Number        string
	Complement    *string
	Neighborhood  string
	City          string
	State         string
	IsDefault     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AuthMethod struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Provider        string
	PasswordHash    *string
	ProviderSubject *string
	CreatedAt       time.Time
	LastUsedAt      *time.Time
}

type Cart struct {
	ID            uuid.UUID
	UserID        *uuid.UUID
	AnonSessionID *string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type CartItem struct {
	ID             uuid.UUID
	CartID         uuid.UUID
	VariantID      uuid.UUID
	Quantity       int32
	UnitPriceCents int64
	AddedAt        time.Time
	UpdatedAt      time.Time
}

type CatalogCategory struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	ParentID  *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CatalogImage struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	VariantID *uuid.UUID
	Url       string
	AltText   string
	Position  int32
	CreatedAt time.Time
	UrlThumb  *string
	UrlMedium *string
	UrlLarge  *string
	// R2 object key prefix (e.g. products/{pid}/{iid})
	StorageKey *string
}

type CatalogVariant struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	Sku        string
	Size       string
	Color      string
	PriceCents *int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Charge struct {
	ID               uuid.UUID
	OrderID          uuid.UUID
	Provider         string
	ProviderChargeID string
	Method           string
	Status           string
	AmountCents      int64
	RawPayload       []byte
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type CheckoutQuote struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	CartFingerprint  string
	LinesSnapshot    []byte
	ShippingSnapshot []byte
	CouponCode       *string
	SubtotalCents    int64
	ShippingCents    int64
	DiscountCents    int64
	TotalCents       int64
	ExpiresAt        time.Time
	CreatedAt        time.Time
	AddressSnapshot  []byte
}

type Coupon struct {
	ID            uuid.UUID
	Code          string
	Type          string
	Value         int64
	ExpiresAt     *time.Time
	UsageLimit    *int32
	UsedCount     int32
	MinOrderCents *int64
	Active        bool
	CreatedAt     time.Time
}

type EmailVerifyToken struct {
	TokenHash  []byte
	UserID     uuid.UUID
	Email      string
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type IdempotencyKey struct {
	Key         string
	UserID      uuid.UUID
	RequestHash string
	OrderID     *uuid.UUID
	Response    []byte
	CreatedAt   time.Time
}

type InventoryStock struct {
	VariantID uuid.UUID
	Available int32
	Reserved  int32
	Version   int32
	UpdatedAt time.Time
}

type Order struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Status           string
	SubtotalCents    int64
	ShippingCents    int64
	DiscountCents    int64
	TotalCents       int64
	CouponCode       *string
	AddressSnapshot  []byte
	ShippingSnapshot []byte
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type OrderItem struct {
	ID              uuid.UUID
	OrderID         uuid.UUID
	VariantID       uuid.UUID
	Quantity        int32
	UnitPriceCents  int64
	ProductSnapshot []byte
	CreatedAt       time.Time
}

type PasswordResetToken struct {
	TokenHash  []byte
	UserID     uuid.UUID
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type StockReservation struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	VariantID uuid.UUID
	Quantity  int32
	Status    string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	EmailVerifiedAt *time.Time
	Name            string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
