// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Address struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	RecipientName string
	PostalCode    string
	Street        string
	Number        string
	Complement    *string
	Neighborhood  string
	City          string
	State         string
	IsDefault     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AuthMethod struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Provider        string
	PasswordHash    *string
	ProviderSubject *string
	CreatedAt       time.Time
	LastUsedAt      *time.Time
}

type Cart struct {
	ID            uuid.UUID
	UserID        *uuid.UUID
	AnonSessionID *string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type CartItem struct {
	ID             uuid.UUID
	CartID         uuid.UUID
	VariantID      uuid.UUID
	Quantity       int32
	UnitPriceCents int64
	AddedAt        time.Time
	UpdatedAt      time.Time
}

type CatalogCategory struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	ParentID  *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CatalogImage struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	VariantID *uuid.UUID
	Url       string
	AltText   string
	Position  int32
	CreatedAt time.Time
	UrlThumb  *string
	UrlMedium *string
	UrlLarge  *string
	// R2 object key prefix (e.g. products/{pid}/{iid})
	StorageKey *string
}

type CatalogVariant struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	Sku        string
	Size       string
	Color      string
	PriceCents *int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type EmailVerifyToken struct {
	TokenHash  []byte
	UserID     uuid.UUID
	Email      string
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type PasswordResetToken struct {
	TokenHash  []byte
	UserID     uuid.UUID
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	EmailVerifiedAt *time.Time
	Name            string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
