// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, user_id, status, subtotal_cents, shipping_cents, discount_cents,
                    total_cents, coupon_code, address_snapshot, shipping_snapshot)
VALUES ($1, $2, 'pending_payment', $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, status, subtotal_cents, shipping_cents, discount_cents, total_cents, coupon_code, address_snapshot, shipping_snapshot, created_at, updated_at
`

type CreateOrderParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	SubtotalCents    int64
	ShippingCents    int64
	DiscountCents    int64
	TotalCents       int64
	CouponCode       *string
	AddressSnapshot  []byte
	ShippingSnapshot []byte
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.SubtotalCents,
		arg.ShippingCents,
		arg.DiscountCents,
		arg.TotalCents,
		arg.CouponCode,
		arg.AddressSnapshot,
		arg.ShippingSnapshot,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.CouponCode,
		&i.AddressSnapshot,
		&i.ShippingSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, variant_id, quantity, unit_price_cents, product_snapshot)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, variant_id, quantity, unit_price_cents, product_snapshot, created_at
`

type CreateOrderItemParams struct {
	OrderID         uuid.UUID
	VariantID       uuid.UUID
	Quantity        int32
	UnitPriceCents  int64
	ProductSnapshot []byte
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.VariantID,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.ProductSnapshot,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VariantID,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.ProductSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, subtotal_cents, shipping_cents, discount_cents, total_cents, coupon_code, address_snapshot, shipping_snapshot, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.CouponCode,
		&i.AddressSnapshot,
		&i.ShippingSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserOrderByID = `-- name: GetUserOrderByID :one
SELECT id, user_id, status, subtotal_cents, shipping_cents, discount_cents, total_cents, coupon_code, address_snapshot, shipping_snapshot, created_at, updated_at FROM orders WHERE id = $1 AND user_id = $2
`

type GetUserOrderByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetUserOrderByID(ctx context.Context, arg GetUserOrderByIDParams) (Order, error) {
	row := q.db.QueryRow(ctx, getUserOrderByID, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.CouponCode,
		&i.AddressSnapshot,
		&i.ShippingSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, variant_id, quantity, unit_price_cents, product_snapshot, created_at FROM order_items WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VariantID,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.ProductSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, status, subtotal_cents, shipping_cents, discount_cents, total_cents, coupon_code, address_snapshot, shipping_snapshot, created_at, updated_at FROM orders WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListOrdersByUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.SubtotalCents,
			&i.ShippingCents,
			&i.DiscountCents,
			&i.TotalCents,
			&i.CouponCode,
			&i.AddressSnapshot,
			&i.ShippingSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTransition = `-- name: RecordTransition :exec
INSERT INTO order_status_transitions (order_id, from_status, to_status, reason, actor)
VALUES ($1, $2, $3, $4, $5)
`

type RecordTransitionParams struct {
	OrderID    uuid.UUID
	FromStatus *string
	ToStatus   string
	Reason     string
	Actor      string
}

func (q *Queries) RecordTransition(ctx context.Context, arg RecordTransitionParams) error {
	_, err := q.db.Exec(ctx, recordTransition,
		arg.OrderID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.Actor,
	)
	return err
}

const setOrderStatus = `-- name: SetOrderStatus :exec
UPDATE orders SET status = $1, updated_at = now() WHERE id = $2
`

type SetOrderStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) error {
	_, err := q.db.Exec(ctx, setOrderStatus, arg.Status, arg.ID)
	return err
}

const transitionOrderStatus = `-- name: TransitionOrderStatus :execrows
UPDATE orders SET status = $1, updated_at = now()
WHERE id = $2 AND status = $3
`

type TransitionOrderStatusParams struct {
	ToStatus   string
	ID         uuid.UUID
	FromStatus string
}

func (q *Queries) TransitionOrderStatus(ctx context.Context, arg TransitionOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionOrderStatus, arg.ToStatus, arg.ID, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
