// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :exec
UPDATE password_reset_tokens
SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, consumePasswordResetToken, tokenHash)
	return err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :execrows
DELETE FROM password_reset_tokens
WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findPasswordResetToken = `-- name: FindPasswordResetToken :one
SELECT token_hash, user_id, expires_at, consumed_at, created_at
FROM password_reset_tokens
WHERE token_hash = $1
`

func (q *Queries) FindPasswordResetToken(ctx context.Context, tokenHash []byte) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, findPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertPasswordResetToken = `-- name: InsertPasswordResetToken :exec
INSERT INTO password_reset_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type InsertPasswordResetTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, insertPasswordResetToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}
