// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO catalog_products (
    id, slug, name, description, brand, category_id,
    base_price_cents, currency, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, slug, name, description, brand, category_id, base_price_cents, currency, status, created_at, updated_at
`

type CreateProductParams struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Description    string
	Brand          string
	CategoryID     uuid.UUID
	BasePriceCents int64
	Currency       string
	Status         string
}

type CreateProductRow struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Description    string
	Brand          string
	CategoryID     uuid.UUID
	BasePriceCents int64
	Currency       string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.CategoryID,
		arg.BasePriceCents,
		arg.Currency,
		arg.Status,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.CategoryID,
		&i.BasePriceCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM catalog_products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, slug, name, description, brand, category_id, base_price_cents, currency, status, created_at, updated_at
FROM catalog_products WHERE id = $1
`

type GetProductByIDRow struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Description    string
	Brand          string
	CategoryID     uuid.UUID
	BasePriceCents int64
	Currency       string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.CategoryID,
		&i.BasePriceCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, slug, name, description, brand, category_id, base_price_cents, currency, status, created_at, updated_at
FROM catalog_products WHERE slug = $1
`

type GetProductBySlugRow struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Description    string
	Brand          string
	CategoryID     uuid.UUID
	BasePriceCents int64
	Currency       string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.CategoryID,
		&i.BasePriceCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminProducts = `-- name: ListAdminProducts :many
SELECT id, slug, name, description, brand, category_id, base_price_cents, currency, status, created_at, updated_at
FROM catalog_products
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAdminProductsParams struct {
	Limit  int32
	Offset int32
}

type ListAdminProductsRow struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Description    string
	Brand          string
	CategoryID     uuid.UUID
	BasePriceCents int64
	Currency       string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListAdminProducts(ctx context.Context, arg ListAdminProductsParams) ([]ListAdminProductsRow, error) {
	rows, err := q.db.Query(ctx, listAdminProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminProductsRow
	for rows.Next() {
		var i ListAdminProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.CategoryID,
			&i.BasePriceCents,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedProducts = `-- name: ListPublishedProducts :many
SELECT id, slug, name, description, brand, category_id, base_price_cents, currency, status, created_at, updated_at
FROM catalog_products
WHERE status = 'published'
  AND ($2::uuid IS NULL OR category_id = $2)
  AND ($3::bigint IS NULL OR base_price_cents >= $3)
  AND ($4::bigint IS NULL OR base_price_cents <= $4)
  AND ($5::text IS NULL OR brand = $5)
ORDER BY created_at DESC, id DESC
LIMIT $1
`

type ListPublishedProductsParams struct {
	Limit      int32
	CategoryID *uuid.UUID
	MinPrice   *int64
	MaxPrice   *int64
	Brand      *string
}

type ListPublishedProductsRow struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Description    string
	Brand          string
	CategoryID     uuid.UUID
	BasePriceCents int64
	Currency       string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListPublishedProducts(ctx context.Context, arg ListPublishedProductsParams) ([]ListPublishedProductsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedProducts,
		arg.Limit,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Brand,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedProductsRow
	for rows.Next() {
		var i ListPublishedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.CategoryID,
			&i.BasePriceCents,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE catalog_products
SET slug = $2, name = $3, description = $4, brand = $5, category_id = $6,
    base_price_cents = $7, currency = $8, status = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, name, description, brand, category_id, base_price_cents, currency, status, created_at, updated_at
`

type UpdateProductParams struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Description    string
	Brand          string
	CategoryID     uuid.UUID
	BasePriceCents int64
	Currency       string
	Status         string
}

type UpdateProductRow struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Description    string
	Brand          string
	CategoryID     uuid.UUID
	BasePriceCents int64
	Currency       string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.CategoryID,
		arg.BasePriceCents,
		arg.Currency,
		arg.Status,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.CategoryID,
		&i.BasePriceCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
