// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
)

type Querier interface {
	HealthCheck(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
