// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const searchProducts = `-- name: SearchProducts :many
SELECT id, slug, name, description, brand, category_id, base_price_cents, currency, status, created_at, updated_at,
    ts_rank(search_vector, plainto_tsquery('portuguese', $1)) AS rank
FROM catalog_products
WHERE status = 'published'
  AND (
    search_vector @@ plainto_tsquery('portuguese', $1)
    OR name % $1
  )
ORDER BY rank DESC, created_at DESC
LIMIT $2
`

type SearchProductsParams struct {
	PlaintoTsquery string
	Limit          int32
}

type SearchProductsRow struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Description    string
	Brand          string
	CategoryID     uuid.UUID
	BasePriceCents int64
	Currency       string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Rank           float32
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsRow
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.CategoryID,
			&i.BasePriceCents,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
