// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: variants.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createImage = `-- name: CreateImage :one
INSERT INTO catalog_images (id, product_id, variant_id, url, alt_text, position,
                            url_thumb, url_medium, url_large, storage_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, product_id, variant_id, url, alt_text, position, created_at, url_thumb, url_medium, url_large, storage_key
`

type CreateImageParams struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	VariantID  *uuid.UUID
	Url        string
	AltText    string
	Position   int32
	UrlThumb   *string
	UrlMedium  *string
	UrlLarge   *string
	StorageKey *string
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (CatalogImage, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.ID,
		arg.ProductID,
		arg.VariantID,
		arg.Url,
		arg.AltText,
		arg.Position,
		arg.UrlThumb,
		arg.UrlMedium,
		arg.UrlLarge,
		arg.StorageKey,
	)
	var i CatalogImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.Url,
		&i.AltText,
		&i.Position,
		&i.CreatedAt,
		&i.UrlThumb,
		&i.UrlMedium,
		&i.UrlLarge,
		&i.StorageKey,
	)
	return i, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO catalog_variants (id, product_id, sku, size, color, price_cents)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, sku, size, color, price_cents, created_at, updated_at
`

type CreateVariantParams struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	Sku        string
	Size       string
	Color      string
	PriceCents *int64
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (CatalogVariant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ID,
		arg.ProductID,
		arg.Sku,
		arg.Size,
		arg.Color,
		arg.PriceCents,
	)
	var i CatalogVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Size,
		&i.Color,
		&i.PriceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteImageByID = `-- name: DeleteImageByID :exec
DELETE FROM catalog_images WHERE id = $1
`

func (q *Queries) DeleteImageByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteImageByID, id)
	return err
}

const deleteImagesByProduct = `-- name: DeleteImagesByProduct :exec
DELETE FROM catalog_images WHERE product_id = $1
`

func (q *Queries) DeleteImagesByProduct(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteImagesByProduct, productID)
	return err
}

const deleteVariantsByProduct = `-- name: DeleteVariantsByProduct :exec
DELETE FROM catalog_variants WHERE product_id = $1
`

func (q *Queries) DeleteVariantsByProduct(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariantsByProduct, productID)
	return err
}

const listImagesByProduct = `-- name: ListImagesByProduct :many
SELECT id, product_id, variant_id, url, alt_text, position, created_at, url_thumb, url_medium, url_large, storage_key FROM catalog_images WHERE product_id = $1 ORDER BY position, created_at
`

func (q *Queries) ListImagesByProduct(ctx context.Context, productID uuid.UUID) ([]CatalogImage, error) {
	rows, err := q.db.Query(ctx, listImagesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogImage
	for rows.Next() {
		var i CatalogImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VariantID,
			&i.Url,
			&i.AltText,
			&i.Position,
			&i.CreatedAt,
			&i.UrlThumb,
			&i.UrlMedium,
			&i.UrlLarge,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT id, product_id, sku, size, color, price_cents, created_at, updated_at FROM catalog_variants WHERE product_id = $1 ORDER BY sku
`

func (q *Queries) ListVariantsByProduct(ctx context.Context, productID uuid.UUID) ([]CatalogVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogVariant
	for rows.Next() {
		var i CatalogVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Size,
			&i.Color,
			&i.PriceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
